language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
